// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// readPDZ25
Rcpp::List readPDZ25(std::string fileName);
RcppExport SEXP _rPDZ_readPDZ25(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ25(fileName));
    return rcpp_result_gen;
END_RCPP
}
// readPDZManual
NumericVector readPDZManual(std::string fileName, int start, int size);
RcppExport SEXP _rPDZ_readPDZManual(SEXP fileNameSEXP, SEXP startSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZManual(fileName, start, size));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ24
std::vector<float> readPDZ24(const std::string& fileName, int start);
RcppExport SEXP _rPDZ_readPDZ24(SEXP fileNameSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ24(fileName, start));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ24FloatFetch
float readPDZ24FloatFetch(std::string fileName, int position);
RcppExport SEXP _rPDZ_readPDZ24FloatFetch(SEXP fileNameSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ24FloatFetch(fileName, position));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ24DoubleFetch
double readPDZ24DoubleFetch(std::string fileName, int position);
RcppExport SEXP _rPDZ_readPDZ24DoubleFetch(SEXP fileNameSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ24DoubleFetch(fileName, position));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ
NumericVector readPDZ(std::string fileName, int start, int size);
RcppExport SEXP _rPDZ_readPDZ(SEXP fileNameSEXP, SEXP startSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ(fileName, start, size));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ25OG
std::vector<float> readPDZ25OG(std::string fileName);
RcppExport SEXP _rPDZ_readPDZ25OG(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ25OG(fileName));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ25eVCH
float readPDZ25eVCH(std::string fileName);
RcppExport SEXP _rPDZ_readPDZ25eVCH(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ25eVCH(fileName));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ25LiveTime
float readPDZ25LiveTime(std::string fileName);
RcppExport SEXP _rPDZ_readPDZ25LiveTime(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ25LiveTime(fileName));
    return rcpp_result_gen;
END_RCPP
}
// readPDZ25FloatFetch
float readPDZ25FloatFetch(std::string fileName, int position);
RcppExport SEXP _rPDZ_readPDZ25FloatFetch(SEXP fileNameSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(readPDZ25FloatFetch(fileName, position));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rPDZ_readPDZ25", (DL_FUNC) &_rPDZ_readPDZ25, 1},
    {"_rPDZ_readPDZManual", (DL_FUNC) &_rPDZ_readPDZManual, 3},
    {"_rPDZ_readPDZ24", (DL_FUNC) &_rPDZ_readPDZ24, 2},
    {"_rPDZ_readPDZ24FloatFetch", (DL_FUNC) &_rPDZ_readPDZ24FloatFetch, 2},
    {"_rPDZ_readPDZ24DoubleFetch", (DL_FUNC) &_rPDZ_readPDZ24DoubleFetch, 2},
    {"_rPDZ_readPDZ", (DL_FUNC) &_rPDZ_readPDZ, 3},
    {"_rPDZ_readPDZ25OG", (DL_FUNC) &_rPDZ_readPDZ25OG, 1},
    {"_rPDZ_readPDZ25eVCH", (DL_FUNC) &_rPDZ_readPDZ25eVCH, 1},
    {"_rPDZ_readPDZ25LiveTime", (DL_FUNC) &_rPDZ_readPDZ25LiveTime, 1},
    {"_rPDZ_readPDZ25FloatFetch", (DL_FUNC) &_rPDZ_readPDZ25FloatFetch, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rPDZ(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
