# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_rpdz_cpp_rcpp_hello_world`)
}

readPDZ24 <- function(fileName, start, size) {
    .Call(`_rpdz_cpp_readPDZ24`, fileName, start, size)
}

readPDZ25 <- function(fileName, start, size) {
    .Call(`_rpdz_cpp_readPDZ25`, fileName, start, size)
}

getevch24 <- function(fileName, start, size) {
    .Call(`_rpdz_cpp_getevch24`, fileName, start, size)
}

