# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readPDZ25 <- function(fileName) {
    .Call(`_rPDZ_readPDZ25`, fileName)
}

readPDZManual <- function(fileName, start, size) {
    .Call(`_rPDZ_readPDZManual`, fileName, start, size)
}

readPDZ24 <- function(fileName, start) {
    .Call(`_rPDZ_readPDZ24`, fileName, start)
}

readPDZ24FloatFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ24FloatFetch`, fileName, position)
}

readPDZ24DoubleFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ24DoubleFetch`, fileName, position)
}

readPDZ <- function(fileName, start, size) {
    .Call(`_rPDZ_readPDZ`, fileName, start, size)
}

readPDZ25OG <- function(fileName) {
    .Call(`_rPDZ_readPDZ25OG`, fileName)
}

readPDZ25eVCH <- function(fileName) {
    .Call(`_rPDZ_readPDZ25eVCH`, fileName)
}

readPDZ25LiveTime <- function(fileName) {
    .Call(`_rPDZ_readPDZ25LiveTime`, fileName)
}

readPDZ25FloatFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ25FloatFetch`, fileName, position)
}

