# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readPDZ24 <- function(fileName, start, size) {
    .Call(`_rPDZ_readPDZ24`, fileName, start, size)
}

readPDZ <- function(fileName, start, size) {
    .Call(`_rPDZ_readPDZ`, fileName, start, size)
}

readPDZ25 <- function(fileName) {
    .Call(`_rPDZ_readPDZ25`, fileName)
}

