# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readPDZ24 <- function(fileName) {
    .Call(`_rPDZ_readPDZ24`, fileName)
}

readPDZ24FloatFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ24FloatFetch`, fileName, position)
}

readPDZ24DoubleFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ24DoubleFetch`, fileName, position)
}

readPDZ <- function(fileName, start, size) {
    .Call(`_rPDZ_readPDZ`, fileName, start, size)
}

readPDZ25 <- function(fileName) {
    .Call(`_rPDZ_readPDZ25`, fileName)
}

readPDZ25eVCH <- function(fileName) {
    .Call(`_rPDZ_readPDZ25eVCH`, fileName)
}

readPDZ25LiveTime <- function(fileName) {
    .Call(`_rPDZ_readPDZ25LiveTime`, fileName)
}

readPDZ25FloatFetch <- function(fileName, position) {
    .Call(`_rPDZ_readPDZ25FloatFetch`, fileName, position)
}

getPDZSpectrumCount <- function(fileName) {
    .Call(`_rPDZ_getPDZSpectrumCount`, fileName)
}

getPDZFormatVersion <- function(fileName) {
    .Call(`_rPDZ_getPDZFormatVersion`, fileName)
}

isPDZv25Format <- function(fileName) {
    .Call(`_rPDZ_isPDZv25Format`, fileName)
}

readPDZSpectrum <- function(fileName, spectrumIndex) {
    .Call(`_rPDZ_readPDZSpectrum`, fileName, spectrumIndex)
}

getPDZInfo <- function(fileName) {
    .Call(`_rPDZ_getPDZInfo`, fileName)
}

getPDZLiveTime <- function(fileName, spectrumIndex) {
    .Call(`_rPDZ_getPDZLiveTime`, fileName, spectrumIndex)
}

getPDZeVCh <- function(fileName, spectrumIndex) {
    .Call(`_rPDZ_getPDZeVCh`, fileName, spectrumIndex)
}

getPDZTubeVoltage <- function(fileName, spectrumIndex) {
    .Call(`_rPDZ_getPDZTubeVoltage`, fileName, spectrumIndex)
}

getPDZMetadata <- function(fileName) {
    .Call(`_rPDZ_getPDZMetadata`, fileName)
}

readAllPDZSpectra <- function(fileName) {
    .Call(`_rPDZ_readAllPDZSpectra`, fileName)
}

getPDZDataFrames <- function(fileName) {
    .Call(`_rPDZ_getPDZDataFrames`, fileName)
}

